import {
  FAMILY_HISTORY_SCOPE_INFO,
  FAMILY_HISTORY_TOOLS,
  NEVER_EXPOSED,
  NEVER_PERMITTED,
} from "@/lib/mcp/catalog";
import { SUPPORT_DESK_URL } from "@/lib/site/supportDesk";

export function GET() {
  const body = [
    "# Assist With Family History — agent setup",
    "",
    "Product: Assist With Family History is the user's durable private family-history research-to-story workspace. The assistant reasons, researches, compares, corrects, and drafts; the product owns identity, permissions, records, provenance, workflow state, and human review.",
    "MCP endpoint: https://assistwithfamilyhistory.com/mcp",
    "Transport: remote Streamable HTTP MCP with OAuth. Modern 2026-07-28 requests and stateless 2025-era fallback share one tool factory.",
    "Setup page: https://assistwithfamilyhistory.com/ai",
    `Support: ${SUPPORT_DESK_URL} is the one support desk for every Assist With site. No Assist With site has a support, feedback, or privacy email address, so never tell a person to email this product.`,
    "",
    "## Approval comes from the person, not from signing in",
    "Signing in proves whose vault this is. It does not decide what your connection may do. The first call from a connection the person has not approved returns the machine error GRANT_REQUIRED. When you see it, stop and ask the person to approve the connection at https://assistwithfamilyhistory.com/settings/ai, choosing which permissions and which records it covers. Do not retry in a loop.",
    "Other grant errors: GRANT_REVOKED (they turned it off — stop), GRANT_EXPIRED (ask them to renew), SCOPE_NOT_GRANTED (use only the tools tools/list returned for this connection), OUTSIDE_GRANT_BOUNDARY (that record is outside what they approved).",
    "tools/list is filtered by what the person approved. Trust it; it is the exact surface this connection has.",
    "",
    "## Required workflow",
    "1. Call family_history_get_brief first.",
    "2. Use family_history_search before creating records that may already exist.",
    "3. Use family_history_get_context to hydrate stable IDs and updatedAt before corrections.",
    "4. For a source that touches several people at once — a census page, a family group sheet — use family_history_save_records: one call, per-item results, and rows that fail come back named while the rest of the pass is still saved. Use family_history_save_complete_result when the pass must be all-or-nothing.",
    "5. Preserve source/citation provenance, evidence-versus-conclusion status, conflicts, uncertainty, and blocked research honestly.",
    "6. Queue context never grants domain-write authority. Use Queue tools only for work assigned to oauth-chosen-ai.",
    "",
    "## Permissions a person can approve",
    ...FAMILY_HISTORY_SCOPE_INFO.map(
      (info) => `- ${info.scope} — ${info.label}. ${info.grants} Limit: ${info.limit}`,
    ),
    "",
    "## Tools",
    "Canonical names are family_history_*. The pre-namespace names are kept as deprecated aliases on the same handlers and the same permission, so a client that connected earlier keeps working; prefer the canonical name.",
    ...FAMILY_HISTORY_TOOLS.map(
      (tool) =>
        `- ${tool.name} (${tool.requiredScope}${tool.writes ? ", writes" : ", read-only"})${tool.alias ? ` [alias: ${tool.alias}]` : ""} — ${tool.humanSummary}`,
    ),
    "",
    "## Never available through this connection",
    ...NEVER_EXPOSED.map((entry) => `- Never exposed: ${entry}`),
    ...NEVER_PERMITTED.map((entry) => `- Never permitted: ${entry}`),
    "",
    "## Safety",
    "- Never provide or invent userId, ownerId, workspaceId, vaultOwnerId, or tenant IDs. The server derives the vault from verified OAuth.",
    "- Never publish, delete, merge identities, change sharing, or perform external FamilySearch actions through this MCP surface.",
    "- Never ask a person for a link to a private file, and never fetch one yourself. Use family_history_get_evidence; it returns reviewed, AI-allowed items as content blocks and tells you honestly what it could not deliver and why.",
    "- Broad discovery withholds living-person notes. Person hydration includes only reviewed AI-allowed loose context and media.",
    "- Evidence facts do not silently overwrite canonical person conclusions. Save candidates/conflicts and let the person review.",
    "- Story writes are draft or review only. Published stories are human-gated and cannot be edited here.",
    "- Reuse operationId for a safe retry of exactly the same write. Reuse createKey for the same durable record intent.",
    "",
    "## Current / Partial / Later",
    "Current in production: endpoint, OAuth challenge/metadata, bounded reads, server-derived owner, replay-safe writes, canonical UI-visible records, explicit PKCE consent, one disposable named-client research-to-story lifecycle, and exact synthetic cleanup.",
    "Built and awaiting deployed proof: person-approved product grants, server-enforced scopes, record boundaries, immediate revocation, batch record saves, and protected evidence delivery.",
    "Partial: family_history_get_evidence returns real text for person documents, which are stored here. Media rows currently hold a file reference rather than bytes in most cases, and those items come back skipped with BYTES_NOT_AVAILABLE rather than a pretend delivery.",
    "Partial after exact deployed proof: Client ID Metadata Document discovery, dynamic client registration, broad client compatibility, fresh-device email verification, mobile setup, and refresh/reconnect.",
    "Later: publishing, deletion, identity merge, export, external provider actions, wider client matrix.",
    "",
    "If tools look stale after a deploy: disconnect the MCP server, reconnect it, sign in again, and confirm the family_history_* names above appear before writing.",
    "",
  ].join("\n");
  return new Response(body, { headers: { "Content-Type": "text/plain; charset=utf-8", "Cache-Control": "public, max-age=300" } });
}
